name: Publish
on:
  release:
    types: [released]
jobs:
  cargo:
    name: Cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
      - name: Login to registry
        uses: actions-rs/cargo@v1
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          command: login
          args: "$CARGO_REGISTRY_TOKEN"
      - name: Publish crate
        uses: actions-rs/cargo@v1
        with:
          command: publish
