name: Publish
on:
  release:
    types: [released]
jobs:
  cargo:
    name: Cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install stable toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Check version number
        run: ./scripts/check-version.sh
      - name: Login to registry
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo +${{steps.toolchain.outputs.name}} login "$CARGO_REGISTRY_TOKEN"
      - name: Publish crate
        run: cargo +${{steps.toolchain.outputs.name}} publish
