name: Publish
on:
  release:
    types: [released]
jobs:
  cargo:
    name: Cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          default: true
      - env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo login "$CARGO_REGISTRY_TOKEN"
      - run: cargo publish
